<template>
  <section class="inventory-page">
    <div class="inventory-stats"><article v-for="stat in stats" :key="stat.label"><p>{{ stat.label }}</p><strong :class="stat.color">{{ stat.value }}</strong></article></div>
    <article class="inventory-panel"><header><h2>Inventory Status</h2><button @click="showAdd = true"><v-icon icon="mdi-plus" /> Add Stock</button></header><div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Current Stock</th><th>Sold This Month</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="item in inventory" :key="item.name"><td><div class="product"><span><v-icon icon="mdi-cube-outline" /></span><strong>{{ item.name }}</strong></div></td><td>{{ item.category }}</td><td class="stock-number">{{ item.stock }}</td><td class="stock-number">{{ item.sold }}</td><td><em :class="item.stock < 250 ? 'low' : 'in-stock'">{{ item.stock < 250 ? 'Low Stock' : 'In Stock' }}</em></td><td><button class="restock" @click="restock(item)"><v-icon icon="mdi-plus" /> Restock</button></td></tr></tbody></table></div></article>
    <v-dialog v-model="showAdd" max-width="440"><v-card class="dialog"><v-card-title>Add Stock</v-card-title><v-card-text><v-select :items="inventory.map(item => item.name)" label="Product" variant="outlined" /><v-text-field label="Quantity" type="number" variant="outlined" /></v-card-text><v-card-actions><v-spacer /><v-btn @click="showAdd = false">Cancel</v-btn><v-btn color="primary" variant="flat" @click="saveStock">Add Stock</v-btn></v-card-actions></v-card></v-dialog>
  </section>
</template>

<script setup lang="ts">
  import { ref } from 'vue'
  const emit = defineEmits<{ notice: [message: string] }>()
  const showAdd = ref(false)
  const stats = [{ label: 'Total Products', value: '6', color: '' }, { label: 'Low Stock Items', value: '2', color: 'orange' }, { label: 'Out of Stock', value: '0', color: 'red' }, { label: 'Total Value', value: '₱1,074,470.00', color: '' }]
  const inventory = [{ name: 'TIKBOY Embutido (Pork)', category: 'Combo Packs', stock: 180, sold: 945 }, { name: 'TIKBOY Longganisa (Big)', category: 'Classic', stock: 450, sold: 1247 }, { name: 'TIKBOY Longganisa (Small)', category: 'Classic', stock: 380, sold: 1056 }, { name: 'TIKBOY Spicy Longganisa', category: 'Spicy', stock: 320, sold: 892 }, { name: 'TIKBOY Embutido (Chicken)', category: 'Premium', stock: 240, sold: 678 }, { name: 'TIKBOY Sweet Longganisa', category: 'Classic', stock: 410, sold: 734 }]
  const restock = (item: { name: string }) => emit('notice', `Restock ${item.name}`)
  const saveStock = () => { showAdd.value = false; emit('notice', 'Stock added') }
</script>

<style scoped>
  .inventory-page { padding:39px 35px; }.inventory-stats { display:grid; grid-template-columns:repeat(4,1fr); gap:30px; margin-bottom:40px; }.inventory-stats article { min-height:137px; padding:30px; border:1px solid #e0e5ec; border-radius:20px; background:#fff; }.inventory-stats p { margin:0 0 10px; color:#355173; font-size:17px; }.inventory-stats strong { color:#071d3c; font-size:38px; }.inventory-stats .orange { color:#f04b00; }.inventory-stats .red { color:#e60000; }.inventory-panel { overflow:hidden; border:1px solid #e0e5ec; border-radius:20px; background:#fff; box-shadow:0 2px 3px rgba(11,32,62,.05); }.inventory-panel header { display:flex; align-items:center; justify-content:space-between; padding:30px; }.inventory-panel h2 { margin:0; color:#071d3c; font-size:25px; }.inventory-panel header button { display:flex; align-items:center; gap:15px; height:46px; padding:0 18px; border:0; border-radius:10px; background:#d92e40; color:white; font-weight:700; }.table-wrap { overflow-x:auto; }table { width:100%; min-width:1080px; border-collapse:collapse; }th { height:64px; background:#fafbfc; color:#071b39; font-size:16px; text-align:left; }th:first-child,td:first-child { padding-left:30px; }th:last-child,td:last-child { padding-right:30px; }td { padding:20px 15px; border-top:1px solid #e1e6ec; color:#2f496b; font-size:16px; }.product { display:flex; align-items:center; gap:15px; }.product span { display:grid; place-items:center; width:50px; height:50px; border-radius:12px; background:#fde9ed; color:#de3043; }.product strong { color:#071d3c; font-size:18px; }.stock-number { color:#081d3d; font-size:18px; font-weight:700; text-align:center; }em { display:inline-block; padding:5px 10px; border-radius:10px; font-size:14px; font-style:normal; }.low { background:#fff7be; color:#e99800; }.in-stock { background:#d8fae5; color:#00a548; }.restock { display:flex; align-items:center; gap:12px; height:42px; padding:0 14px; border:1px solid #d0d9e4; border-radius:10px; background:white; font-weight:600; }.dialog { border-radius:16px; }@media(max-width:1200px){.inventory-page{padding:28px}.inventory-stats{gap:20px}}@media(max-width:860px){.inventory-stats{grid-template-columns:repeat(2,1fr)}}@media(max-width:540px){.inventory-page{padding:18px 15px}.inventory-stats{grid-template-columns:1fr}.inventory-panel header{padding:22px 18px}.inventory-panel h2{font-size:22px}}
</style>
